apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      containers:
      - name: backend
        image: my-backend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000