apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      containers:
      - name: backend
        image: my-backend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: project-backend-service
  namespace: devops
spec:
  selector:
    app: project-backend
  ports:
  - port: 80
    targetPort: 3000