apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend-v2
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend-v2
  template:
    metadata:
      labels:
        app: project-backend-v2
    spec:
      containers:
      - name: backend-v2
        image: my-backend:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: project-backend-v2-service
  namespace: devops
spec:
  selector:
    app: project-backend-v2
  ports:
  - port: 80
    targetPort: 3001